// Traces the six section icons by just.call.me.l into SVG, in two layers:
// "ink" (the white line art) and "tone" (the grey fills, like the tablet in
// Glossary). The layers come from art-src/ink-*.png and tone-*.png,
// which are the original tiles upscaled six times with the purple ground
// keyed out. Writes src/icons.ts. Run when the art changes: `bun run trace`.
import potrace from "potrace";

const names = ["character", "lore", "glossary", "schedule", "clips", "fan-art"];
const trace = (file: string, turdSize: number) =>
  new Promise<string>((resolve, reject) =>
    potrace.trace(file, { turdSize, alphaMax: 1, optCurve: true, optTolerance: 0.2, threshold: 128, blackOnWhite: true }, (err: Error | null, svg: string) =>
      err ? reject(err) : resolve(svg),
    ),
  );
const pathOf = (svg: string) => [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]).join(" ").trim();

const out: Record<string, { viewBox: string; ink: string; tone: string }> = {};
for (const name of names) {
  const inkSvg = await trace(`art-src/ink-${name}.png`, 6);
  const toneSvg = await trace(`art-src/tone-${name}.png`, 80);
  const w = inkSvg.match(/width="(\d+)"/)![1];
  const h = inkSvg.match(/height="(\d+)"/)![1];
  out[name] = { viewBox: `0 0 ${w} ${h}`, ink: pathOf(inkSvg), tone: pathOf(toneSvg) };
  console.log(name, w, h, out[name].ink.length, out[name].tone.length);
}
await Bun.write(
  "src/icons.ts",
  `// Generated by scripts/trace.ts from the section icons by just.call.me.l. Do not edit by hand.\nexport const ICONS: Record<string, { viewBox: string; ink: string; tone: string }> = ${JSON.stringify(out)};\n`,
);
